# Generated by Django 4.2 on 2026-02-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elective_types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('language', models.TextField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tracks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.programs')),
            ],
        ),
        migrations.CreateModel(
            name='electives',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('instructor', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.TextField(max_length=3)),
                ('status', models.IntegerField(default=0)),
                ('degree_year', models.TextField(max_length=5)),
                ('prerequisite', models.TextField()),
                ('elective_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.elective_types')),
            ],
        ),
    ]
