# Generated by Django 4.2 on 2026-04-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_year', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveType',
            fields=[
                ('elective_type_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLanguage',
            fields=[
                ('language', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.programlanguage'),
        ),
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('elective_language', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('prerequisite', models.TextField(blank=True)),
                ('degree_year', models.ManyToManyField(blank=True, to='catalog.degree')),
                ('elective_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.electivetype')),
                ('program_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.programlanguage')),
            ],
        ),
    ]
