# Generated by Django 4.2 on 2026-04-21 19:28

from django.db import migrations

def add_initial_languages(apps, schema_editor):
    ProgramLanguage = apps.get_model('catalog', 'ProgramLanguage')

    languages = [
        ProgramLanguage(language='ENG'),
        ProgramLanguage(language='RUS'),
    ]

    ProgramLanguage.objects.bulk_create(languages)

def add_initial_degree(apps, schema_editor):
    Degree = apps.get_model('catalog', 'Degree')

    degrees = [
        Degree(degree_year='BS1'),
        Degree(degree_year='BS2'),
        Degree(degree_year='MS1'),
        Degree(degree_year='MS2'),
    ]

    Degree.objects.bulk_create(degrees)

def add_initial_elective_types(apps, schema_editor):
    ElectiveType = apps.get_model('catalog', 'ElectiveType')

    elective_types = [
        ElectiveType(elective_type_name='TECH'),
        ElectiveType(elective_type_name='HUM'),
        ElectiveType(elective_type_name='MATH'),
    ]

    ElectiveType.objects.bulk_create(elective_types)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_languages),
        migrations.RunPython(add_initial_degree),
        migrations.RunPython(add_initial_elective_types),
    ]
