# Generated by Django 4.2 on 2026-04-21 19:30

from django.db import migrations

def add_initial_programs(apps, schema_editor):
    ProgramLanguage = apps.get_model('catalog', 'ProgramLanguage')
    Program = apps.get_model('catalog', 'Program')

    russian = ProgramLanguage.objects.get(language='RUS')
    english = ProgramLanguage.objects.get(language='ENG')

    programs = [
        Program(
            name='CSE',
            language=english
        ),
        Program(
            name='DSAI',
            language=english
        ),
        Program(
            name='MFAI',
            language=russian
        ),
    ]

    Program.objects.bulk_create(programs)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_languages_degree_electivetypes'),
    ]

    operations = [
        migrations.RunPython(add_initial_programs),
    ]
