# Generated by Django 4.2 on 2026-02-24 13:29

from django.db import migrations

def add_initial_languages(apps, schema_editor):
    ProgramLanguages = apps.get_model('catalog', 'ProgramLanguages')

    languages = [
        ProgramLanguages(language='ENG'),
        ProgramLanguages(language='RUS'),
    ]

    ProgramLanguages.objects.bulk_create(languages)

def add_initial_degree(apps, schema_editor):
    Degree = apps.get_model('catalog', 'Degree')

    degrees = [
        Degree(degree_year='BS1'),
        Degree(degree_year='BS2'),
        Degree(degree_year='MS1'),
        Degree(degree_year='MS2'),
    ]

    Degree.objects.bulk_create(degrees)

def add_initial_elective_types(apps, schema_editor):
    ElectiveTypes = apps.get_model('catalog', 'ElectiveTypes')

    elective_types = [
        ElectiveTypes(elective_type_name='TECH'),
        ElectiveTypes(elective_type_name='HUM'),
        ElectiveTypes(elective_type_name='MATH'),
    ]

    ElectiveTypes.objects.bulk_create(elective_types)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_program_id_tracks_program'),
    ]

    operations = [
        migrations.RunPython(add_initial_languages),
        migrations.RunPython(add_initial_degree),
        migrations.RunPython(add_initial_elective_types),
    ]
