# Generated by Django 4.2 on 2026-04-21 19:34

from django.db import migrations

def add_initial_electives(apps, schema_editor):
    Elective = apps.get_model('catalog', 'Elective')

    ElectiveType = apps.get_model('catalog', 'ElectiveType')
    tech = ElectiveType.objects.get(elective_type_name='TECH')
    hum = ElectiveType.objects.get(elective_type_name='HUM')
    math = ElectiveType.objects.get(elective_type_name='MATH')

    ProgramLanguage = apps.get_model('catalog', 'ProgramLanguage')
    rus = ProgramLanguage.objects.get(language='RUS')
    eng = ProgramLanguage.objects.get(language='ENG')

    Degree = apps.get_model('catalog', 'Degree')
    bs1 = Degree.objects.get(degree_year='BS1')
    bs2 = Degree.objects.get(degree_year='BS2')
    ms1 = Degree.objects.get(degree_year='MS1')
    ms2 = Degree.objects.get(degree_year='MS2')

    elective1 = Elective.objects.create(
            name='Architecture of Computing Devices',
            instructor='Mikhail Kuskov',
            description='The main objective of the course is to introduce students to the design process of modern computing devices',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='None required'
        )
    elective1.degree_year.add(bs1, bs2)

    elective2 = Elective.objects.create(
            name='Business Analysis in IT',
            instructor='Ivan Goskov',
            description='Business Analysis in IT has become a high-demand trend in recent years',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='None required'
        )
    elective2.degree_year.add(bs1, bs2)

    elective3 = Elective.objects.create(
            name='Business Intelligence and Datawarehouse Systems',
            instructor='Ivan Lukovic',
            description='The primary objective is to give students advanced knowledge in the development of Business Intelligence (BI) and Data Warehouse (DW) software systems, as well as various aspects of Data Science (DS) applications, in support of generation of business knowledge, necessary for strategic and tactical management in organization systems',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='None required'
        )
    elective3.degree_year.add(bs2)

    elective4 = Elective.objects.create(
            name='Challenges of Object Oriented Programming',
            instructor='Yegor Bugayenko',
            description='The course is a critical review of the current situation in object-oriented programming, especially in Java, C++, Ruby, and JavaScript worlds.',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Apache'
        )
    elective4.degree_year.add(bs2)

    elective5 = Elective.objects.create(
            name='Computer Chess',
            instructor='Paolo Ciancarini',
            description='Chess posed a significant challenge in artificial intelligence research during the 20th century. Efforts to solve the game faced a combinatorial explosion due to its seemingly simple setup of thirty-two pieces on sixty-four squares, resulting in more potential chess games than atoms in the universe',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Non'
        )
    elective5.degree_year.add(bs2)

    elective6 = Elective.objects.create(
            name='Golang & Flutter: Rapid Cross-Platform Development',
            instructor='Kharin Timur',
            description='This course teaches a modern full-stack framework for building high-performance, scalable applications that can evolve from rapid prototypes to enterprise-grade solutions. By combining Golang’s backend efficiency with Flutter’s cross-platform UI agility, students learn to validate product hypotheses quickly while ensuring reliability and scalability from day one. ',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='Non'
        )
    elective6.degree_year.add(bs1, bs2)

    elective7 = Elective.objects.create(
            name='How to Launch the Robot?',
            instructor='Ruslan Damindarov',
            description='Цель данного курса: Показать основы работы с сенсорами, методами компьютерного зрения, часто применяемые в робототехнических системах. Эти навыки критичны для карьеры в робототехнике, автоматизации и компьютерном зрении, позволяя работать с реальными задачами — от сортировки объектов до автономной навигации роботов.',
            elective_type=tech,
            program_language=eng,
            elective_language='русский',
            status=1,
            prerequisite='Non'
        )
    elective7.degree_year.add(bs1)

    elective8 = Elective.objects.create(
            name='Introduction to 3D Modeling',
            instructor='Egor Dmitriev',
            description='This course provides an introductory exploration into the fundamentals of 3D modeling, focusing on developing foundational skills in creating and manipulating 3D objects using Blender 3D. Through hands-on labs and projects, students will learn essential techniques using industry-standard software to craft 3D models for various applications such as animation, gaming, and product design.',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='Basic computer literacy\nNo prior experience in 3D modeling is required, but creativity and a willingness to learn are welcomed.'
        )
    elective8.degree_year.add(bs1, bs2)

    elective9 = Elective.objects.create(
            name='Introduction to Electronic and Logic Circuits',
            instructor='Amer Al Badr',
            description='This course provides an introduction to electronic circuits and extends some concepts from Theoretical Computer Science to logic circuits. Students will learn about fundamental electronic components such as diodes, transistors, and op-amps, along with basic electrical laws and their applications in electronic circuits. The course covers topics including combinational and sequential logic, state machines, and circuit implementation and testing.',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Mathematical Analysis\nPhysics Fundamentals\nTheoretical Computer Science'
        )
    elective9.degree_year.add(bs1)

    elective10 = Elective.objects.create(
            name='Real-Time Scheduling Theory',
            instructor='Artem Burmyakov',
            description='The course covers the basic theoretical aspects of real-time scheduling theory. We will start with the introduction to the available mathematical models for real-time systems, including periodic and sporadic tasks, worst-case execution timing, hard and soft task deadlines. ',
            elective_type=tech,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Non'
        )
    elective10.degree_year.add(bs1, bs2)

    elective11 = Elective.objects.create(
            name='Applied Economics: Introduction to IT Entrepreneurship',
            instructor='Tatiana Kamaletdinova',
            description='The main goals of this course are: Describing the basic characteristics of the Russian economic system, with an emphasis on the role of private property, the price system, competition, and entrepreneurship.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Non'
        )
    elective11.degree_year.add(bs1)

    elective12 = Elective.objects.create(
            name='Basics of Product Management',
            instructor='Julia Metelskaya',
            description='The course aims to provide students with necessary knowledge and tools to become a product manager. The students will learn product management skills and tools that will help them to build digital products.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Non'
        )
    elective12.degree_year.add(bs1, bs2)

    elective13 = Elective.objects.create(
            name='Branding & Marketing in IT Industry',
            instructor='Marko Pezer',
            description='At IT universities, courses usually focus on technical skills that enable students to realize their ideas and create software, websites, and applications. However, statistics say that only 10 of startups in the IT industry survive the first year. Its difficult to pinpoint one reason for startup failure, but a common case is that startups fail to position themselves successfully in the market, which results in them not reaching an audience.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='Non'
        )
    elective13.degree_year.add(bs1, bs2)
    
    elective14 = Elective.objects.create(
            name='Career and Leadership',
            instructor='Alina Valencia',
            description='The target audience of this course are those planning to model a successful career and develop their leadership skills. \nThis course is dedicated to the main aspects and modern trends in career modelling and leadership to help students to create their own career path becoming the leaders of their lives, to develop professional skills and to be in high demand on the international labor market. The main purpose of this course is to form the students’ vision of effective career modelling and to develop the competencies needed for the successful career and personal growth. ',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Non'
        )
    elective14.degree_year.add(bs1)
    
    elective15 = Elective.objects.create(
            name='Cyberlaw: Data, Ethics and Digital Property',
            instructor='Mikhail Zhuravlev',
            description='The course “Cyber Law: Data, Ethics and Digital Property” covers the basics of information technology and intellectual property law. The course addresses the issues of personal data protection, information and Internet law, copyright law in the digital environment. All the topics are considered not only from the point of Russian law, but also in a comparative legal context. Particular attention is paid to the ethical and legal aspects of machine learning and artificial intelligence, such as legal liability, legal grounds for data scraping, legal protection of AI-generated works, etc.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='Non'
        )
    elective15.degree_year.add(bs2)
    
    elective16 = Elective.objects.create(
            name='Design Thinking',
            instructor='Roman Efimov',
            description='Design Thinking + AI for Change: How to Create Meaningful Products, Services, and Human ExperiencesCourse Motto: Learn how to rapidly and mindfully design products and solutions that transform human behavior and experience — using the tools of design thinking, the power of AI, and your own sense of meaning. Because the World Doesnt Need More Features, It Needs Better Experiences!',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Non'
        )
    elective16.degree_year.add(bs1, bs2)
    
    elective17 = Elective.objects.create(
            name='Startup CEO Toolkit',
            instructor='Vasil Zakiev',
            description='In this course, students will engage in practical management exercises for a startup CEO. This includes everything from creating a pitch deck to tracking progress, establishing Operations, Marketing, Financial management, HR, and understanding the legal aspects of registering a company and intellectual property.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='Non'
        )
    elective17.degree_year.add(bs2)
    
    elective18 = Elective.objects.create(
            name='Tech Startup Design',
            instructor='Zhanara Semenova',
            description='This course is for individuals who want to find and develop a startup idea and build a team to execute it.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Non'
        )
    elective18.degree_year.add(ms1, ms2)
    
    elective19 = Elective.objects.create(
            name='Unit Economics, Financial Modelling & Business Valuation',
            instructor='Maxim Popov',
            description='The target audience of the course are those who want to make impact on financial result of the companies they work in or the startups they lead.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=1,
            prerequisite='Non'
        )
    elective19.degree_year.add(ms1)
    
    elective20 = Elective.objects.create(
            name='UX/UI Design',
            instructor='Haytham Hamed',
            description='This course focuses on User Experience (UX) and User Interface (UI) design, tailored for the unique challenges and needs of growing companies. It combines lectures and practical lab sessions to teach the principles and best practices of UX/UI design in the startup context.',
            elective_type=hum,
            program_language=eng,
            elective_language='english',
            status=0,
            prerequisite='Interest in product design & design thinking.'
        )
    elective20.degree_year.add(bs1, bs2, ms1, ms2)
    
    elective21 = Elective.objects.create(
            name='Инженерия продуктовых решений',
            instructor='Марк Гаджимурадов',
            description='Цель курса – сформировать у студентов комплексное понимание процесса управления IT-продуктом, предоставить необходимые знания и практические инструменты для успешного создания и развития цифровых решений. \nСтуденты освоят современные методологии управления и навыки, которые позволят им эффективно решать задачи на всех этапах жизненного цикла управления продуктом',
            elective_type=hum,
            program_language=eng,
            elective_language='русский',
            status=0,
            prerequisite='Предварительные знания не требуются'
        )
    elective21.degree_year.add(ms2)
    

    elective22 = Elective.objects.create(
            name='Методы и подходы к запуску роботизированных систем',
            instructor='Руслан Даминдаров',
            description='Цель данного курса: Показать основы работы с сенсорами, методами компьютерного зрения, часто применяемые в робототехнических системах. Эти навыки критичны для карьеры в робототехнике, автоматизации и компьютерном зрении, позволяя работать с реальными задачами — от сортировки объектов до автономной навигации роботов.',
            elective_type=tech,
            program_language=rus,
            elective_language='русский',
            status=0,
            prerequisite='-'
        )
    elective22.degree_year.add(bs1)
    
    elective23 = Elective.objects.create(
            name='Общая физика (углубленный курс)',
            instructor='Кирилл Клименок',
            description='Изучение дисциплины обеспечивает формирование и развитие компетенций обучающихся в области общей физики, их применение для решения различных прикладных задач в рамках профессиональной деятельности. В ходе освоения дисциплины обучающиеся рассматривают основные квантовой механики, а также их применение для описания моделей окружающего мира',
            elective_type=math,
            program_language=rus,
            elective_language='русский',
            status=1,
            prerequisite='-'
        )
    elective23.degree_year.add(bs1, bs2)
    
    elective24 = Elective.objects.create(
            name='Экономические механизмы и их наиболее актуальные',
            instructor='Александр Филатов, Алексей Савватеев',
            description='Теория экономических механизмов – это современный раздел экономики, изучающий модели принятия оптимальных решений в условиях разнонаправленных интересов участников взаимодействия. Административный путь регулирования часто не приводит к максимизации общественного благосостояния.',
            elective_type=tech,
            program_language=rus,
            elective_language='русский',
            status=1,
            prerequisite='-'
        )
    elective24.degree_year.add(bs1)

    elective25 = Elective.objects.create(
            name='Теория функций комплексного переменного',
            instructor='Сергей Городецкий',
            description='Комплексные числа. Алгебраическая, тригонометрическая и показательная. Формы комплексного числа. Расширенная комплексная плоскость, стереографическая проекция \nДифференцируемость функций комплексного переменного. Условия Коши–Римана. Регулярные функции',
            elective_type=math,
            program_language=rus,
            elective_language='русский',
            status=0,
            prerequisite='-'
        )
    elective25.degree_year.add(bs1)

    elective26 = Elective.objects.create(
            name='Введение в функциональный анализ',
            instructor='П.А. Останин',
            description='Изучение дисциплины обеспечивает формирование и развитие компетенций обучающихся в области методов функционального анализа, их применение для решения различных прикладных задач в рамках профессиональной деятельности. В ходе освоения дисциплины обучающиеся рассматривают фундаментальные вопросы, необходимые современному исследователю в области моделирования, вычислительной математики, теории вероятностей, оптимизации, машинного обучения:',
            elective_type=tech,
            program_language=rus,
            elective_language='русский',
            status=0,
            prerequisite='-'
        )
    elective26.degree_year.add(bs2)

    elective27 = Elective.objects.create(
            name='Прикладная математика: искусство и ремесло вычислений',
            instructor='В.А. Гордин',
            description='Предполагается заметное количество домашних работ, включающих в себя необходимость численного решения, построения графиков и анализа полученных численно решений. Студенты должны быть проинформированы, что прохождение данного курса будет трудоемко. Цель курса подготовить слушателей к самостоятельной работе в различных научных лабораториях: уметь строить математические модели, использовать и аналитические, и компьютерные методы, а также их комбинации для анализа свойств решений таких моделей, уметь графически представлять и анализировать полученные результаты',
            elective_type=math,
            program_language=rus,
            elective_language='русский',
            status=1,
            prerequisite='-'
        )
    elective27.degree_year.add(bs1, bs2)

    elective28 = Elective.objects.create(
            name='Теория информации',
            instructor='А.А. Фролов',
            description='Данный курс является вводным курсом по теории информации. В первой части рассматриваются измерение информации, взаимная информация, энтропия, оценка пропускной способности одно- и многопользовательских каналов. Во второй части рассматриваются основы теории кодирования, такие как блочные коды, линейные коды, ограничения на параметры кодов и наиболее популярные алгебраические методы кодирования (коды Хэмминга, Рида-Маллера, БЧХ и Рида-Соломона)',
            elective_type=tech,
            program_language=rus,
            elective_language='русский',
            status=0,
            prerequisite='-'
        )
    elective28.degree_year.add(bs2)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_tracks'),
    ]

    operations = [
        migrations.RunPython(add_initial_electives),
    ]
