# Generated by Django 4.2 on 2026-02-24 14:31

from django.db import migrations

def add_initial_programs(apps, schema_editor):
    ProgramLanguages = apps.get_model('catalog', 'ProgramLanguages')
    Programs = apps.get_model('catalog', 'Programs')

    russian = ProgramLanguages.objects.get(language='RUS')
    english = ProgramLanguages.objects.get(language='ENG')

    programs = [
        Programs(
            name='CSE',
            language=english
        ),
        Programs(
            name='DSAI',
            language=english
        ),
        Programs(
            name='MFAI',
            language=russian
        ),
    ]

    Programs.objects.bulk_create(programs)

class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0004_add_initial_languages_degree_electivetypes'),
    ]

    operations = [
        migrations.RunPython(add_initial_programs),
    ]
