# Generated by Django 4.2 on 2026-02-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0002_rename_stream_id_iteration_streams_and_more'),
        ('catalog', '0003_rename_program_id_tracks_program'),
        ('catalog', '0004_alter_electives_degree_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('elective_language', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('prerequisite', models.TextField()),
                ('degree_year', models.ManyToManyField(blank=True, to='catalog.degree')),
            ],
        ),
        migrations.RenameModel(
            old_name='programs',
            new_name='Program',
        ),
        migrations.RenameModel(
            old_name='tracks',
            new_name='Track',
        ),
        migrations.RenameModel(
            old_name='ElectiveTypes',
            new_name='ElectiveType',
        ),
        migrations.RenameModel(
            old_name='ProgramLanguages',
            new_name='ProgramLanguage',
        ),
        migrations.DeleteModel(
            name='electives',
        ),
        migrations.AddField(
            model_name='elective',
            name='elective_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.electivetype'),
        ),
        migrations.AddField(
            model_name='elective',
            name='program_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.programlanguage'),
        ),
    ]
