# Generated by Django 4.2 on 2026-05-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_electives'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveTrackException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.elective')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track')),
            ],
            options={
                'db_table': 'catalog_elective_track_exception',
                'unique_together': {('elective', 'track')},
            },
        ),
    ]
