# Generated by Django 4.2 on 2026-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_initial_electives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='prerequisite',
            field=models.TextField(blank=True),
        ),
    ]
