# Generated by Django 4.2 on 2026-02-24 16:41

from django.db import migrations

def add_initial_tracks(apps, schema_editor):
    Program = apps.get_model('catalog', 'Program')
    Track = apps.get_model('catalog', 'Track')

    cse = Program.objects.get(name='CSE')
    dsai = Program.objects.get(name='DSAI')

    tracks = [
        Track(
            name='DS',
            program=dsai
        ),
        Track(
            name='AI',
            program=dsai
        ),
        Track(
            name='RO',
            program=dsai
        ),
        Track(
            name='SD',
            program=cse
        ),
        Track(
            name='GD',
            program=cse
        ),
    ]

    Track.objects.bulk_create(tracks)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_initial_programs'),
    ]

    operations = [
        migrations.RunPython(add_initial_tracks),
    ]
