# Generated by Django 4.2 on 2026-04-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('mail', models.CharField(unique=True)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('mail', models.CharField(unique=True)),
                ('degree_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.degree')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.program')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.track')),
            ],
        ),
    ]
