# Generated by Django 4.2 on 2026-04-21 19:37

from django.db import migrations

def add_initial_admin(apps, schema_editor):
    Admin = apps.get_model('login', 'Admin')

    admins = [
        Admin(
            mail='admin@innopolis.university',
            role=0
        ),
        Admin(
            mail='admin.student@innopolis.university',
            role=1
        )
    ]
    Admin.objects.bulk_create(admins)

def add_initial_student(apps, schema_editor):
    Student = apps.get_model('login', 'Student')

    Program = apps.get_model('catalog', 'Program')
    cse = Program.objects.get(name='CSE')
    dsai = Program.objects.get(name='DSAI')
    mfai = Program.objects.get(name='MFAI')

    Track = apps.get_model('catalog', 'Track')
    ds = Track.objects.get(name='DS')
    ai = Track.objects.get(name='AI')
    ro = Track.objects.get(name='RO')
    sd = Track.objects.get(name='SD')
    gd = Track.objects.get(name='GD')

    Degree = apps.get_model('catalog', 'Degree')
    bs1 = Degree.objects.get(degree_year='BS1')
    bs2 = Degree.objects.get(degree_year='BS2')
    ms1 = Degree.objects.get(degree_year='MS1')
    ms2 = Degree.objects.get(degree_year='MS2')

    students = [
        Student(
            mail='a.kalashnikova@innopolis.university',
            degree_year=bs1,
            program=cse
        ),
        Student(
            mail='s.mukhamedshina@innopolis.university',
            degree_year=bs2,
            program=dsai,
            track=ai
        ),
        Student(
            mail='m.karpova@innopolis.university',
            degree_year=bs2,
            program=cse,
            track=sd
        ),
        Student(
            mail='v.gorbacheva@innopolis.university',
            degree_year=bs2,
            program=dsai,
            track=ai
        ),
        Student(
            mail='d.potapova@innopolis.university',
            degree_year=bs1,
            program=mfai,
        ),
    ]
    Student.objects.bulk_create(students)

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('catalog', '0005_add_electives'),
    ]

    operations = [
        migrations.RunPython(add_initial_admin),
        migrations.RunPython(add_initial_student),
    ]
