services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: MakeYourChoice_backend
    volumes:
      - ./backend:/app
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - MakeYourChoice__network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: MakeYourChoice_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - backend
    networks:
      - MakeYourChoice__network
  

  db:
    image: postgres:15-alpine
    container_name: MakeYourChoice_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - MakeYourChoice__network

    
volumes:
  postgres_data:

networks:
  MakeYourChoice__network:
    driver: bridge
