/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Аутентификация по email
         * @description Загружается один раз при входе в сессию. Last submissions загружаются здесь же — отдельного эндпоинта нет, фронт обновляет данные локально в рамках сессии.
         */
        get: {
            parameters: {
                query: {
                    email: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Данные пользователя в зависимости от роли */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentResponse"] | components["schemas"]["AdminResponse"] | components["schemas"]["AdminStudentResponse"];
                    };
                };
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "User not found"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/electives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список элективов */
        get: {
            parameters: {
                query?: {
                    /** @description 0 — архив, 1 — активный, -1 — удалён */
                    status?: 0 | 1 | -1;
                    elective_type?: string;
                    program_language?: string;
                    /** @description Поиск по name, description, instructor */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список элективов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Elective"][];
                    };
                };
            };
        };
        put?: never;
        /** Создать электив */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "New elective",
                     *       "instructor": "Test instructor",
                     *       "description": "Example of POST elective command",
                     *       "elective_language": "english",
                     *       "program_language": "ENG"
                     *     }
                     */
                    "application/json": components["schemas"]["ElectiveCreate"];
                };
            };
            responses: {
                201: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/electives/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить электив по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Электив */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Elective"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить поля электива (включая удаление через status -1)
         * @description Удаление реализовано через PATCH — передаём `{"status": -1}`. Возвращает `{"status": "archived"}`.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ElectiveUpdate"];
                };
            };
            responses: {
                200: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/electives/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Архивировать электив (status → 0) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Электив архивирован */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "archived"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список программ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список программ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": 1,
                         *         "language": "ENG",
                         *         "name": "CSE"
                         *       },
                         *       {
                         *         "id": 2,
                         *         "language": "ENG",
                         *         "name": "DSAI"
                         *       },
                         *       {
                         *         "id": 3,
                         *         "language": "RUS",
                         *         "name": "MFAI"
                         *       }
                         *     ]
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /** Создать программу */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "DSAI2",
                     *       "language": "RUS"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                201: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить программу */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Изменить программу */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        language?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список треков */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список треков */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": 1,
                         *         "program": 2,
                         *         "name": "DS"
                         *       },
                         *       {
                         *         "id": 2,
                         *         "program": 2,
                         *         "name": "AI"
                         *       },
                         *       {
                         *         "id": 4,
                         *         "program": 1,
                         *         "name": "SD"
                         *       }
                         *     ]
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /** Создать трек */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "AAI2",
                     *       "program": "2"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                201: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить трек
         * @description Возвращает 400 если трек используется студентами.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
                /** @description Трек используется студентами */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "error",
                         *       "message": "Track is used by existing students"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Изменить трек */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "program": 1,
                     *       "name": "AAI3"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                200: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/elective_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список типов элективов */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список типов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "elective_type_name": "TECH"
                         *       },
                         *       {
                         *         "elective_type_name": "HUM"
                         *       },
                         *       {
                         *         "elective_type_name": "MATH"
                         *       }
                         *     ]
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /** Создать тип электива */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "elective_type_name": "TEST"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                201: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elective_types/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить тип электива
         * @description PATCH недоступен — elective_type_name является Primary Key. Возвращает 400 если тип используется в элективах.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example TEST */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
                /** @description Тип используется в элективах */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "error",
                         *       "message": "Elective type is used by existing electives"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types_by_language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Кол-во элективов по языкам программ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Статистика по языкам */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "types_by_language": [
                         *         {
                         *           "language": "ENG",
                         *           "count": 2
                         *         },
                         *         {
                         *           "language": "RUS",
                         *           "count": 2
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Все настройки одним запросом
         * @description Возвращает языки, типы элективов, программы с треками и кол-вом приоритетов. Поле elective_type_settings пока заглушка — приоритеты не подтягиваются.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Настройки */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Все исключения + все треки + доступные элективы
         * @description Формат исключения — [электив] запрещён для [трек]. Доступные элективы — те, у которых нет ни одного исключения.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Данные для страницы исключений */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "exceptions": [
                         *         {
                         *           "id": 2,
                         *           "elective": {
                         *             "id": 6,
                         *             "name": "Golang & Flutter: Rapid Cross-Platform Development"
                         *           },
                         *           "track": {
                         *             "id": 1,
                         *             "name": "DS"
                         *           },
                         *           "created_at": "2026-05-05T20:13:27.153481Z"
                         *         }
                         *       ],
                         *       "all_tracks": [
                         *         {
                         *           "id": 1,
                         *           "name": "DS"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "AI"
                         *         }
                         *       ],
                         *       "available_electives": [
                         *         {
                         *           "id": 7,
                         *           "name": "How to Launch the Robot?"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /** Создать исключение */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "elective_id": 6,
                     *       "track_id": 2
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Исключение создано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "message": "Exception created successfully",
                         *       "data": {
                         *         "id": 1,
                         *         "elective": {
                         *           "id": 6,
                         *           "name": "Golang & Flutter: Rapid Cross-Platform Development"
                         *         },
                         *         "track": {
                         *           "id": 2,
                         *           "name": "AI"
                         *         },
                         *         "created_at": "2026-05-05T19:12:00Z"
                         *       }
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                /** @description elective_id и track_id не переданы / исключение уже существует / электив архивирован или удалён */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Электив или трек не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить исключение */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Исключение удалено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "message": "Exception deleted successfully"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Изменить исключение */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Исключение обновлено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "message": "Exception updated successfully",
                         *       "data": {
                         *         "id": 1,
                         *         "elective": {
                         *           "id": 7,
                         *           "name": "How to Launch the Robot?"
                         *         },
                         *         "track": {
                         *           "id": 3,
                         *           "name": "DS"
                         *         },
                         *         "created_at": "2026-05-05T19:12:00Z"
                         *       }
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                /** @description Не передано ни одно поле / комбинация (электив, трек) уже существует / электив архивирован */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Exception, электив или трек не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список итераций + настройки активной/неактивированной
         * @description Запрашивается один раз при переходе на страницу Semesters Management и после создания новой итерации. Если есть итерация со статусом 0 или 1 — возвращаем её настройки и статус (status 0 → кнопка "activate", status 1 → кнопка "deactivate"). Если таких нет — возвращаем пустую форму для заполнения. Под настройками включаются все доступные элективы для разных языков программ и годов.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список итераций и настройки текущей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            iterations?: {
                                id?: number;
                                /** @example 26-SUM */
                                name?: string;
                                status?: number;
                            }[];
                            /** @description Настройки активной/неактивированной итерации. null если таких нет. */
                            current?: components["schemas"]["SemesterDetail"];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Создать итерацию с потоками
         * @description status 0 — сохранить без активации ("Save"), status 1 — сохранить и сразу активировать ("Save and activate").
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "iteration": "26-SUM",
                     *       "study_year": "BS1",
                     *       "program_language": "ENG",
                     *       "programs": [
                     *         "DSAI",
                     *         "CSE"
                     *       ],
                     *       "electives": [
                     *         2,
                     *         65,
                     *         3,
                     *         8,
                     *         32,
                     *         16
                     *       ],
                     *       "elective_types": [
                     *         "HUM",
                     *         "TECH"
                     *       ],
                     *       "status": 0
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                201: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Настройки конкретной итерации */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Настройки итерации */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SemesterDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Редактировать итерацию (включая активацию/деактивацию)
         * @description Недоступен для итераций со статусом 2 (уже прошедшие). Установить status 1 можно только если заполнены все поля: дедлайн, потоки, название. Удаление через PATCH со status -1.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": unknown;
                };
            };
            responses: {
                200: components["responses"]["Success"];
                /** @description Итерация уже завершена (статус 2) / Не заполнены все поля для активации */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/semesters/excel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Скачать Excel-файл итерации
         * @description Возвращает Excel-файл с тремя листами: легенда (краткие названия элективов), история голосований студентов, последние голосования студентов.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Excel-файл */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список потоков */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список потоков */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stream"][];
                    };
                };
            };
        };
        put?: never;
        /** Создать поток */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StreamCreate"];
                };
            };
            responses: {
                201: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить поток по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Поток */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stream"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Удалить поток */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Изменить поток */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StreamCreate"];
                };
            };
            responses: {
                200: components["responses"]["Success"];
                400: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/streams/{id}/elective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список элективов в потоке */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Элективы потока */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Elective"][];
                    };
                };
            };
        };
        put?: never;
        /** Добавить элективы в поток */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "electiveIds": [
                     *         1,
                     *         2,
                     *         3
                     *       ]
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Элективы добавлены */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "added"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/{id}/elective/{electiveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить электив из потока */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                    electiveId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Электив удалён из потока */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "removed"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отправить / перезаписать выбор элективов
         * @description Без авторизации. Каждый новый POST перезаписывает предыдущий выбор студента для данного типа электива в данной итерации.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "student_id": 1,
                     *       "iteration_id": 4,
                     *       "elective_type": "TECH",
                     *       "electives": [
                     *         {
                     *           "priority": 1,
                     *           "elective_id": 6
                     *         },
                     *         {
                     *           "priority": 3,
                     *           "elective_id": 7
                     *         },
                     *         {
                     *           "priority": 5,
                     *           "elective_id": 8
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                201: components["responses"]["Success"];
                /** @description Дублирующиеся элективы / элективы неактивны / элективы недоступны для студента */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Студент, итерация или тип электива не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List suggestions (admin only)
         * @description Returns all suggestions ordered by creation date descending. Each item includes edit_token so the admin can build the edit link. Requires X-User-Email header with an admin email.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by status */
                    status?: "pending" | "approved" | "rejected";
                };
                header: {
                    "X-User-Email": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of suggestions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Suggestion"][];
                    };
                };
                400: components["responses"]["Error"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Submit a course suggestion (no auth required)
         * @description Anyone can suggest a course without authentication. The suggestion is created with status=pending and waits for admin review.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Introduction to Quantum Computing",
                     *       "instructor": "Alice Ivanova",
                     *       "description": "A course on the fundamentals of quantum computing",
                     *       "elective_language": "english",
                     *       "format": "online",
                     *       "prerequisite": "Linear Algebra, Probability Theory",
                     *       "contact": "alice@example.com"
                     *     }
                     */
                    "application/json": components["schemas"]["SuggestionCreate"];
                };
            };
            responses: {
                /** @description Suggestion submitted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "message": "Your suggestion has been submitted and is pending review"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a suggestion (admin only)
         * @description Sets status to approved and creates a draft elective (status=0) from the suggestion data. program_language and elective_type are left null — the admin fills them in later via PATCH /electives/{id} and activates the elective manually. Requires X-User-Email header with an admin email.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Email": string;
                };
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suggestion approved, draft elective created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "message": "Suggestion approved",
                         *       "elective_id": 42
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                /** @description Suggestion is already approved */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "error",
                         *       "message": "Suggestion is already approved"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a suggestion (admin only)
         * @description Sets status to rejected. Returns only a success response — use GET /suggestions/{id}/edit-link to obtain the author's edit link separately. Requires X-User-Email header with an admin email.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Email": string;
                };
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suggestion rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "message": "Suggestion rejected"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                /** @description Cannot reject an already approved suggestion */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "error",
                         *       "message": "Cannot reject an already approved suggestion"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{id}/edit-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the author edit link for a suggestion (admin only)
         * @description Returns the frontend URL the admin can share with the author so they can edit their suggestion without authentication. Requires X-User-Email header with an admin email.
         */
        get: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Email": string;
                };
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Edit link */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "edit_link": "http://localhost:3000/suggestions/edit/a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/edit/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get suggestion by edit token (author, no auth)
         * @description Allows the author to open their suggestion via a unique link without authentication. Only available for suggestions with status pending or rejected.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suggestion data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Suggestion"];
                    };
                };
                /** @description Approved suggestions cannot be edited */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "error",
                         *       "message": "Approved suggestions cannot be edited"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit suggestion by token (author, no auth)
         * @description The author can update their suggestion using the link received from the admin. Only available for suggestions with status pending or rejected. After editing, the status is automatically reset to pending.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Introduction to Quantum Computing (updated)",
                     *       "instructor": "Alice Ivanova",
                     *       "description": "Updated course description",
                     *       "elective_language": "english",
                     *       "format": "offline",
                     *       "prerequisite": "Linear Algebra",
                     *       "contact": "alice@example.com"
                     *     }
                     */
                    "application/json": components["schemas"]["SuggestionCreate"];
                };
            };
            responses: {
                200: components["responses"]["Success"];
                /** @description Validation error or suggestion already approved */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "error",
                         *       "message": "Approved suggestions cannot be edited"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Elective: {
            id?: number;
            name?: string;
            instructor?: string;
            description?: string;
            /** @example TECH */
            elective_type?: string | null;
            /** @example ENG */
            program_language?: string;
            /** @example english */
            elective_language?: string;
            /** @description 0 — архив, 1 — активный, -1 — удалён */
            status?: number;
            /**
             * @example [
             *       "BS-1",
             *       "BS-2"
             *     ]
             */
            degree_year?: string[];
            prerequisite?: string;
        }
        ElectiveCreate: {
            name: string;
            instructor: string;
            description: string;
            elective_language: string;
            program_language: string;
            elective_type?: string | null;
            /**
             * @description 0 — архив (по умолчанию), 1 — активный
             * @default 0
             */
            status: number;
            degree_year?: string[];
            prerequisite?: string;
        };
        ElectiveUpdate: {
            name?: string;
            instructor?: string;
            description?: string;
            elective_language?: string;
            program_language?: string;
            elective_type?: string;
            /** @description 0 — архивировать, 1 — активировать, -1 — удалить */
            status?: number;
            degree_year?: string[];
            prerequisite?: string;
        };
        Stream: {
            id?: number;
            /** @example BS-1 */
            degree_year?: string;
            /** @example ENG */
            program_lang?: string;
            /** @example TECH */
            elective_type?: string;
            programs?: number[];
            /** @default 5 */
            priorities: number;
        };
        StreamCreate: {
            /** @example BS-1 */
            degree_year: string;
            /** @example ENG */
            program_lang: string;
            /** @example TECH */
            elective_type: string;
            programs: number[];
            /** @default 5 */
            priorities: number;
        };
        StudentResponse: {
            student_id?: number;
            /** @enum {string} */
            role?: "student";
            email?: string;
            student_data?: components["schemas"]["StudentData"];
        };
        AdminResponse: {
            /** @enum {string} */
            role?: "admin";
            email?: string;
            all_electives?: components["schemas"]["Elective"][];
        };
        AdminStudentResponse: {
            /** @enum {string} */
            role?: "admin-student";
            email?: string;
            all_electives?: components["schemas"]["Elective"][];
            student_data?: components["schemas"]["StudentData"];
        };
        StudentData: {
            iteration_id?: number | null;
            /** Format: date-time */
            deadline?: string | null;
            available_electives?: components["schemas"]["ElectiveGroup"][];
            chosen_electives?: components["schemas"]["ChosenGroup"][];
        };
        ElectiveGroup: {
            /** @example TECH */
            elective_type?: string;
            priorities?: number;
            electives?: components["schemas"]["StudentElective"][];
        };
        ChosenGroup: {
            elective_type?: string;
            electives?: {
                priority?: number;
                elective?: components["schemas"]["StudentElective"];
            }[];
        };
        StudentElective: {
            id?: number;
            name?: string;
            instructor?: string;
            description?: string;
            elective_language?: string;
            prerequisite?: string;
        };
        SemesterDetail: {
            id?: number;
            /** @example 26-SUM */
            name?: string;
            /** @example BS1 */
            study_year?: string;
            /** @example ENG */
            program_language?: string;
            programs?: string[];
            electives?: number[];
            elective_types?: string[];
            /** Format: date-time */
            deadline?: string | null;
            /** @description 0 — создана неактивна, 1 — активна, 2 — завершена, -1 — удалена */
            status?: number;
        };
        SuggestionCreate: {
            name: string;
            instructor: string;
            description: string;
            elective_language: string;
            /** @enum {string} */
            format: "online" | "offline";
            prerequisite?: string;
            /** @description Email или иной контакт отправителя */
            contact: string;
        };
        Suggestion: {
            id?: number;
            name?: string;
            instructor?: string;
            description?: string;
            elective_language?: string;
            /** @enum {string} */
            format?: "online" | "offline";
            prerequisite?: string;
            contact?: string;
            /** @enum {string} */
            status?: "pending" | "approved" | "rejected";
            /**
             * Format: uuid
             * @description UUID used to build the author edit link. Always returned in admin endpoints.
             */
            edit_token?: string;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: {
        /** @description Операция выполнена успешно */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "success"
                 *     }
                 */
                "application/json": unknown;
            };
        };
        /** @description Ошибка валидации или бизнес-логики */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error"
                 *     }
                 */
                "application/json": unknown;
            };
        };
        /** @description Объект не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "message": "Not found"
                 *     }
                 */
                "application/json": unknown;
            };
        };
        /** @description Недостаточно прав */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "message": "Forbidden"
                 *     }
                 */
                "application/json": unknown;
            };
        };
    };
    parameters: {
        id: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
