# Generated by Django 4.2 on 2026-04-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_elective_prerequisite'),
        ('iteration', '0005_add_initial_electives_in_streams'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.elective')),
                ('elective_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.electivetype')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteration.iteration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
    ]
