# Generated by Django 4.2 on 2026-04-21 19:49

from django.db import migrations
from datetime import datetime

def add_initial_choice(apps, schema_editor):
    History = apps.get_model('voting', 'History')

    Iteration = apps.get_model('iteration', 'Iteration')
    iteration1 = Iteration.objects.get(id=3) # current
    iteration2 = Iteration.objects.get(id=1) # old


    Student = apps.get_model('login', 'Student')
    student1 = Student.objects.get(id=1) # bs1 cse
    student2 = Student.objects.get(id=3) # bs2 cse


    ElectiveType = apps.get_model('catalog', 'ElectiveType')
    tech = ElectiveType.objects.get(elective_type_name='TECH')
    hum = ElectiveType.objects.get(elective_type_name='HUM')
    math = ElectiveType.objects.get(elective_type_name='MATH')

    Elective = apps.get_model('catalog', 'Elective')

    choices = [
        History(
            iteration=iteration1,
            student=student1,
            elective_type=tech,
            priority=1,
            elective=Elective.objects.get(id=6),
            date = datetime(2026, 4, 9, 12, 0)
        ),
        History(
            iteration=iteration1,
            student=student1,
            elective_type=tech,
            priority=3,
            elective=Elective.objects.get(id=2),
            date = datetime(2026, 4, 9, 12, 0)
        ),
        History(
            iteration=iteration1,
            student=student1,
            elective_type=tech,
            priority=4,
            elective=Elective.objects.get(id=8),
            date = datetime(2026, 4, 9, 12, 0)
        ),
        History(
            iteration=iteration2,
            student=student1,
            elective_type=tech,
            priority=1,
            elective=Elective.objects.get(id=2),
            date = datetime(2025, 4, 3, 12, 0)
        ),
        History(
            iteration=iteration2,
            student=student1,
            elective_type=tech,
            priority=3,
            elective=Elective.objects.get(id=7),
            date = datetime(2025, 4, 3, 12, 0)
        ),
        History(
            iteration=iteration2,
            student=student1,
            elective_type=tech,
            priority=4,
            elective=Elective.objects.get(id=8),
            date = datetime(2025, 4, 3, 12, 0)
        ),
        History(
            iteration=iteration2,
            student=student1,
            elective_type=tech,
            priority=2,
            elective=Elective.objects.get(id=6),
            date = datetime(2025, 4, 3, 12, 0)
        ),
        History(
            iteration=iteration1,
            student=student1,
            elective_type=hum,
            priority=1,
            elective=Elective.objects.get(id=13),
            date = datetime(2026, 4, 8, 12, 0)
        ),
        History(
            iteration=iteration1,
            student=student2,
            elective_type=tech,
            priority=1,
            elective=Elective.objects.get(id=8),
            date = datetime(2026, 4, 5, 13, 0)
        ),
        History(
            iteration=iteration1,
            student=student2,
            elective_type=tech,
            priority=2,
            elective=Elective.objects.get(id=3),
            date = datetime(2026, 4, 5, 13, 0)
        ),
        History(
            iteration=iteration1,
            student=student2,
            elective_type=hum,
            priority=1,
            elective=Elective.objects.get(id=17),
            date = datetime(2026, 4, 5, 13, 0)
        ),
        History(
            iteration=iteration1,
            student=student2,
            elective_type=hum,
            priority=5,
            elective=Elective.objects.get(id=15),
            date = datetime(2026, 4, 5, 13, 0)
        )
    ]

    History.objects.bulk_create(choices)

class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        ('iteration', '0004_add_electives_in_streams'),
    ]

    operations = [
        migrations.RunPython(add_initial_choice),
    ]
