# Generated by Django 4.2 on 2026-04-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('priorities', models.IntegerField(default=5)),
                ('degree_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.degree')),
                ('elective_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.electivetype')),
                ('program_lang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.programlanguage')),
                ('programs', models.ManyToManyField(to='catalog.program')),
            ],
        ),
        migrations.CreateModel(
            name='StreamElectiveRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.elective')),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteration.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=6)),
                ('deadline', models.DateTimeField()),
                ('streams', models.ManyToManyField(to='iteration.stream')),
            ],
        ),
    ]
