# Generated by Django 4.2 on 2026-04-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_elective_prerequisite'),
        ('iteration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamElectiveRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.elective')),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteration.stream')),
            ],
        ),
    ]
