# Generated by Django 4.2 on 2026-04-08 13:16

from django.db import migrations

def add_initial_streams(apps, schema_editor):
    Stream = apps.get_model('iteration', 'Stream')
    ProgramLanguage = apps.get_model('catalog', 'ProgramLanguage')
    rus = ProgramLanguage.objects.get(language='RUS')
    eng = ProgramLanguage.objects.get(language='ENG')

    Degree = apps.get_model('catalog', 'Degree')
    bs1 = Degree.objects.get(degree_year='BS1')
    bs2 = Degree.objects.get(degree_year='BS2')
    ms1 = Degree.objects.get(degree_year='MS1')
    ms2 = Degree.objects.get(degree_year='MS2')

    ElectiveType = apps.get_model('catalog', 'ElectiveType')
    tech = ElectiveType.objects.get(elective_type_name='TECH')
    hum = ElectiveType.objects.get(elective_type_name='HUM')
    math = ElectiveType.objects.get(elective_type_name='MATH')

    Program = apps.get_model('catalog', 'Program')
    cse = Program.objects.get(name='CSE')
    dsai = Program.objects.get(name='DSAI')
    mfai = Program.objects.get(name='MFAI')

    stream1 = Stream.objects.create(
        degree_year=bs1,
        program_lang=eng,
        elective_type=tech, 
        priorities=7
    )
    stream1.programs.add(cse, dsai)

    stream2 = Stream.objects.create(
        degree_year=bs1,
        program_lang=eng,
        elective_type=hum, 
        priorities=6
    )
    stream2.programs.add(cse, dsai)

    stream3 = Stream.objects.create(
        degree_year=bs1,
        program_lang=rus,
        elective_type=hum, 
        priorities=6
    )
    stream3.programs.add(mfai)

    stream4 = Stream.objects.create(
        degree_year=bs1,
        program_lang=rus,
        elective_type=math
    )
    stream4.programs.add(mfai)

    stream5 = Stream.objects.create(
        degree_year=bs2,
        program_lang=eng,
        elective_type=tech, 
        priorities=6
    )
    stream5.programs.add(cse)

    stream6 = Stream.objects.create(
        degree_year=bs2,
        program_lang=eng,
        elective_type=hum
    )
    stream6.programs.add(cse, dsai)

    stream7 = Stream.objects.create(
        degree_year=ms1,
        program_lang=eng,
        elective_type=math,
        priorities=6
    )
    stream7.programs.add(cse, dsai)

class Migration(migrations.Migration):
    dependencies = [
        ('iteration', '0002_streamelectiverelation'),
    ]

    operations = [
        migrations.RunPython(add_initial_streams),
    ]
