# Generated by Django 4.2 on 2026-04-08 21:21

from django.db import migrations
from datetime import datetime

def add_initial_iterations(apps, schema_editor):
    Iteration = apps.get_model('iteration', 'Iteration')
    Stream = apps.get_model('iteration', 'Stream')

    s1 = Stream.objects.get(id=4)
    s2 = Stream.objects.get(id=5)
    s3 = Stream.objects.get(id=6)
    s4 = Stream.objects.get(id=7)
    s5 = Stream.objects.get(id=8)
    s6 = Stream.objects.get(id=9)
    s7 = Stream.objects.get(id=10)

    iter1 = Iteration.objects.create(
        year=25,
        season='SUM',
        deadline=datetime(2025, 5, 1, 12, 0)
    )
    iter1.streams.add(s1, s2, s5, s6)

    iter2 = Iteration.objects.create(
        year=26,
        season='FALL',
        deadline=datetime(2026, 3, 30, 12, 0)
    )
    iter2.streams.add(s7)

    iter3 = Iteration.objects.create(
        year=26,
        season='SUM',
        deadline=datetime(2026, 5, 1, 12, 0)
    )
    iter3.streams.add(s1, s2, s3, s4, s5, s6)


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0003_add_initial_streams_iterations'),
    ]

    operations = [
        migrations.RunPython(add_initial_iterations),
    ]
