# Generated by Django 4.2 on 2026-04-08 21:40

from django.db import migrations

def add_initial_ielectives_in_streams(apps, schema_editor):
    Stream = apps.get_model('iteration', 'Stream')
    Elective = apps.get_model('catalog', 'Elective')
    StreamElective = apps.get_model('iteration', 'StreamElectiveRelation')

    s1 = Stream.objects.get(id=4) # bs1 tech cse, dsai
    s2 = Stream.objects.get(id=5) # bs1 hum cse, dsai
    s3 = Stream.objects.get(id=6) # bs1 hum mfai (rus)
    s4 = Stream.objects.get(id=7) # bs1 math mfai (rus)
    s5 = Stream.objects.get(id=8) # bs2 tech cse
    s6 = Stream.objects.get(id=9) # bs2 hum cse, dsai
    s7 = Stream.objects.get(id=10) # ms1 math cse, dsai

    electives_for_stream1 = [1, 2, 4, 6, 7, 8, 9, 10]
    electives_for_stream2 = [11, 12, 13, 14, 16, 20]
    electives_for_stream3 = [20, 22, 24, 26, 28]
    electives_for_stream4 = [2, 10, 23, 25, 27]
    electives_for_stream5 = [1, 2, 3, 4, 5, 6, 8, 10]
    electives_for_stream6 = [12, 13, 15, 16, 17, 20, 21]
    electives_for_stream7 = [1, 4, 6, 18, 19, 20, 25, 26]

    for i in electives_for_stream1:
        StreamElective.objects.create(stream_id=s1, elective_id=Elective.objects.get(id=i))

    for i in electives_for_stream2:
        StreamElective.objects.create(stream_id=s2, elective_id=Elective.objects.get(id=i))
    
    for i in electives_for_stream3:
        StreamElective.objects.create(stream_id=s3, elective_id=Elective.objects.get(id=i))
    
    for i in electives_for_stream4:
        StreamElective.objects.create(stream_id=s4, elective_id=Elective.objects.get(id=i))
    
    for i in electives_for_stream5:
        StreamElective.objects.create(stream_id=s5, elective_id=Elective.objects.get(id=i))
    
    for i in electives_for_stream6:
        StreamElective.objects.create(stream_id=s6, elective_id=Elective.objects.get(id=i))
    
    for i in electives_for_stream7:
        StreamElective.objects.create(stream_id=s7, elective_id=Elective.objects.get(id=i))

class Migration(migrations.Migration):
    dependencies = [
        ('iteration', '0004_add_initial_iterations'),
    ]

    operations = [
        migrations.RunPython(add_initial_ielectives_in_streams),
    ]
