# Generated by Django 4.2 on 2026-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0004_add_electives_in_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
